// ABOUT (onyx settings root, Bible Chat frame 35). Big serif title + circular X; one grouped card of
// honest, working links (Rate -> repo, Share -> share sheet, Help -> issues, Privacy/Terms -> in-app
// blurb) + a version footer. No fake App Store links (this is a $0 Expo-Go build).
import { Stack, useRouter } from 'expo-router';
import Constants from 'expo-constants';
import { useState } from 'react';
import * as Linking from 'expo-linking';
import { Modal, Pressable, ScrollView, Share, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { PressableScale } from '@/components/ui/pressable-scale';
import { Txt } from '@/components/ui/primitives';
import { Screen } from '@/components/ui/screen';
import { SettingsCard, SettingsHeaderRoot, SettingsRow } from '@/components/ui/settings';
import { haptic } from '@/lib/haptics';
import { c, font, radius, space } from '@/lib/theme';

const REPO = 'https://github.com/MuhammadAhmed43/Daily-Quran';

const LEGAL = {
  privacy: {
    title: 'Privacy',
    body: 'Daily Qur’an keeps your reading history, bookmarks, reflections and preferences on your device. If you create an account, they sync privately to your account so you can continue on another device — we never sell your data or share it with advertisers.\n\nScripture is always rendered from a verified database, never generated by AI. When you ask the assistant a question it is processed only to answer you; any photo you send is analysed in the moment and not stored.',
  },
  terms: {
    title: 'Terms of use',
    body: 'Daily Qur’an is a study aid, offered as-is with no warranty. It is not a substitute for a qualified scholar — for religious rulings, please consult one.\n\nThe app aims to follow mainstream Sunni scholarship and to treat the Qur’an with the reverence it deserves. Please use it kindly and at your own discretion.',
  },
} as const;

export default function AboutScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const [legal, setLegal] = useState<keyof typeof LEGAL | null>(null);
  const version = Constants.expoConfig?.version ?? '1.0.0';

  const open = (url: string) => {
    haptic.light();
    Linking.openURL(url).catch(() => {});
  };
  const share = () => {
    haptic.light();
    Share.share({ message: 'Daily Qur’an — read, reflect and ask about the Qur’an. Come read with me.' }).catch(() => {});
  };
  const showLegal = (k: keyof typeof LEGAL) => {
    haptic.light();
    setLegal(k);
  };

  return (
    <Screen>
      <Stack.Screen options={{ headerShown: false }} />
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <SettingsHeaderRoot title="About" onClose={() => router.back()} />

        <SettingsCard>
          <SettingsRow icon="star-outline" title="Rate Daily Qur’an" onPress={() => open(REPO)} />
          <SettingsRow icon="share-social-outline" title="Share with friends" onPress={share} />
          <SettingsRow icon="construct-outline" title="Help us improve" onPress={() => open(`${REPO}/issues`)} />
          <SettingsRow icon="lock-closed-outline" title="Privacy" onPress={() => showLegal('privacy')} />
          <SettingsRow icon="document-text-outline" title="Terms of use" onPress={() => showLegal('terms')} />
        </SettingsCard>

        {/* DEV: compare the launch-splash concepts on device (remove once a concept is chosen + wired in). */}
        <SettingsCard>
          <SettingsRow
            icon="sparkles-outline"
            title="Preview launch splash"
            subtitle="Compare the splash concepts"
            onPress={() => {
              haptic.light();
              router.push('/splash-preview');
            }}
          />
        </SettingsCard>

        <View style={styles.footer}>
          <Txt variant="caption" color={c.textMuted}>
            Daily Qur’an
          </Txt>
          <Txt variant="caption" color={c.textMuted}>
            Version {version}
          </Txt>
        </View>
      </ScrollView>

      <Modal visible={legal !== null} transparent animationType="slide" onRequestClose={() => setLegal(null)} statusBarTranslucent>
        <View style={styles.modalFill}>
          <Pressable style={styles.modalScrim} onPress={() => setLegal(null)} />
          <View style={[styles.modalPanel, { paddingBottom: insets.bottom + space.card }]}>
            <View style={styles.handle} />
            <Txt variant="h2" style={styles.legalTitle}>
              {legal ? LEGAL[legal].title : ''}
            </Txt>
            <ScrollView style={styles.legalScroll} showsVerticalScrollIndicator={false}>
              <Txt variant="body" color={c.textSecondary} style={styles.legalBody}>
                {legal ? LEGAL[legal].body : ''}
              </Txt>
            </ScrollView>
            <PressableScale style={styles.legalClose} onPress={() => setLegal(null)}>
              <Txt style={styles.legalCloseText}>Close</Txt>
            </PressableScale>
          </View>
        </View>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  scroll: { paddingTop: space.sm, paddingBottom: space.section, gap: space.card },
  footer: { alignItems: 'center', gap: 2, marginTop: space.sm },

  modalFill: { flex: 1, justifyContent: 'flex-end' },
  modalScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.6)' },
  modalPanel: {
    backgroundColor: c.surface2,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.glassLip,
    paddingTop: 10,
    paddingHorizontal: space.gutter,
    maxHeight: '76%',
  },
  handle: { alignSelf: 'center', width: 38, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.18)', marginBottom: 14 },
  legalTitle: { marginBottom: 10 },
  legalScroll: { flexGrow: 0 },
  legalBody: { lineHeight: 24 },
  legalClose: { marginTop: 14, alignItems: 'center', paddingVertical: 14, borderRadius: radius.full, backgroundColor: c.surface3 },
  legalCloseText: { fontFamily: font.sansSemi, fontSize: 15.5, color: c.textPrimary },
});
