// Storyboard ("Stories") data + helpers.
//
// A story is a sequence of panels. Each panel carries app-authored narration and
// art direction, but its scripture is stored ONLY as a reference (e.g. "12:4") —
// the actual Arabic + translation is rendered from the verified bundled Qur'an
// (lib/quran.ts), never hand-typed here. Prophets are never depicted; see
// content/stories/yusuf.md for the full aniconic art spec.

import yusuf from '@/assets/stories/yusuf.json';
import { getAyah, getSurah } from '@/lib/quran';

export type Panel = {
  n: number;
  title: string;
  ref: string; // citation label as shown, e.g. "12:8–9"
  verse: string; // the single ayah to render, "surah:ayah"
  narration: string; // app voice — a retelling, NOT scripture
  visual: string; // aniconic art direction (shown as placeholder until the image exists)
  color: string; // tonal background for the panel, following the indigo→gold arc
  motion?: string; // per-scene Ken Burns "camera move" (see MOTIONS in the player)
  image?: string | null; // remote URL once the illustration is generated + reviewed
  audio?: string | null; // remote URL once the narration MP3 is generated
};

export type Story = {
  id: string;
  title: string;
  subtitle: string;
  arabicName: string;
  surah: number;
  blurb: string;
  panels: Panel[];
};

const STORIES: Story[] = [yusuf as Story];

export function getStories(): Story[] {
  return STORIES;
}

export function getStory(id: string | undefined): Story | undefined {
  if (!id) return undefined;
  return STORIES.find((s) => s.id === id);
}

// Bundled, reviewed panel art. Metro needs static require() literals, so the map is
// explicit. Sized into the app by scripts/bundle-story-art.mjs (originals live in
// content/stories/yusuf-art/, regenerable via scripts/gen-story-art.mjs).
const YUSUF_IMAGES: Record<number, number> = {
  1: require('../assets/stories/yusuf/p01.jpg'),
  2: require('../assets/stories/yusuf/p02.jpg'),
  3: require('../assets/stories/yusuf/p03.jpg'),
  4: require('../assets/stories/yusuf/p04.jpg'),
  5: require('../assets/stories/yusuf/p05.jpg'),
  6: require('../assets/stories/yusuf/p06.jpg'),
  7: require('../assets/stories/yusuf/p07.jpg'),
  8: require('../assets/stories/yusuf/p08.jpg'),
  9: require('../assets/stories/yusuf/p09.jpg'),
  10: require('../assets/stories/yusuf/p10.jpg'),
  11: require('../assets/stories/yusuf/p11.jpg'),
  12: require('../assets/stories/yusuf/p12.jpg'),
  13: require('../assets/stories/yusuf/p13.jpg'),
  14: require('../assets/stories/yusuf/p14.jpg'),
  15: require('../assets/stories/yusuf/p15.jpg'),
  16: require('../assets/stories/yusuf/p16.jpg'),
};

// The bundled illustration for a panel as an <Image source> module id, if we have one.
export function panelImage(storyId: string, n: number): number | undefined {
  return storyId === 'yusuf' ? YUSUF_IMAGES[n] : undefined;
}

// Bundled narrator audio (Deepgram Aura, deep voice). Generated by
// scripts/gen-story-audio.mjs. Static require() literals, same as the images.
const YUSUF_AUDIO: Record<number, number> = {
  1: require('../assets/stories/yusuf-audio/p01.mp3'),
  2: require('../assets/stories/yusuf-audio/p02.mp3'),
  3: require('../assets/stories/yusuf-audio/p03.mp3'),
  4: require('../assets/stories/yusuf-audio/p04.mp3'),
  5: require('../assets/stories/yusuf-audio/p05.mp3'),
  6: require('../assets/stories/yusuf-audio/p06.mp3'),
  7: require('../assets/stories/yusuf-audio/p07.mp3'),
  8: require('../assets/stories/yusuf-audio/p08.mp3'),
  9: require('../assets/stories/yusuf-audio/p09.mp3'),
  10: require('../assets/stories/yusuf-audio/p10.mp3'),
  11: require('../assets/stories/yusuf-audio/p11.mp3'),
  12: require('../assets/stories/yusuf-audio/p12.mp3'),
  13: require('../assets/stories/yusuf-audio/p13.mp3'),
  14: require('../assets/stories/yusuf-audio/p14.mp3'),
  15: require('../assets/stories/yusuf-audio/p15.mp3'),
  16: require('../assets/stories/yusuf-audio/p16.mp3'),
};

// The bundled narration clip for a panel as an audio source module id, if we have one.
export function panelAudio(storyId: string, n: number): number | undefined {
  return storyId === 'yusuf' ? YUSUF_AUDIO[n] : undefined;
}

export type PanelVerse = {
  ar: string;
  en: string;
  ref: string;
  surahEnglish: string;
};

// Resolve a panel's verse reference to the verified Arabic + translation.
export function panelVerse(p: Panel): PanelVerse | null {
  const [s, a] = p.verse.split(':').map(Number);
  const ayah = getAyah(s, a);
  if (!ayah) return null;
  return {
    ar: ayah.ar,
    en: ayah.en,
    ref: p.ref,
    surahEnglish: getSurah(s)?.englishName ?? '',
  };
}
